Met=int(input('Uma distância em metros: '))
print('A medida de \033[1;31m{}m\033[m corresponde a'.format(Met))
print('{} KM'.format(Met/1000))
print('{} HM'.format(Met/100))
print('{} DAM'.format(Met/10))
print('{} M              \033[34m<--------\033[m'.format(Met))
print('{} DM'.format(Met*10))
print('{} CM'.format(Met*100))
print('{} MM'.format(Met*1000))