frase=str(input('Digite uma frase: ')).strip().lower()
esc=str(input('Escolha a letra que quer saber da sua frase: ')).lower()
fra1=frase.split()
fra2=''.join(fra1)
print('Sua frase foi: {}'.format(frase.title()))
print('Sua frase tem {} letras'.format(len(fra2)))
print('Sua escolha de letra que foi a letra {}'.format(esc.upper()))
print('Na sua frase tem {} letras com a sua escolha'.format(fra2.count(esc)))
print('A primeira letra aparece na posição {}'.format(frase.find(esc)+1))
print('E a última letra na sua frase aparece na posição {}'.format(frase.rfind(esc)+1))
